FROM nginx:1.25-alpine

RUN apk update \
    && apk add vim

COPY ../out /usr/share/nginx/html
COPY ../conf.d/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]